# Generated by Django 4.1.1 on 2022-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin_panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delay",
                    models.IntegerField(
                        default=20, verbose_name="Интервал генерации сделок"
                    ),
                ),
            ],
        ),
    ]
