# Generated by Django 4.1.1 on 2022-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_alter_admin_panel_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_panel",
            name="delay",
            field=models.IntegerField(
                default=90, verbose_name="Интервал генерации сделок"
            ),
        ),
    ]
