# Generated by Django 4.1.1 on 2022-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0005_alter_admin_panel_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="event",
            field=models.CharField(default="Growth", max_length=100),
        ),
    ]
