# Generated by Django 4.1.1 on 2022-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_alter_admin_panel_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="exchange",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
