# Generated by Django 4.1.1 on 2022-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0009_alter_deal_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal", name="exchange", field=models.CharField(max_length=100),
        ),
    ]
