# Generated by Django 4.1.1 on 2022-09-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0010_alter_deal_exchange"),
    ]

    operations = [
        migrations.DeleteModel(name="Admin_panel",),
    ]
