# Generated by Django 4.1.1 on 2022-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0012_adminpanel"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="type",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
