# Generated by Django 4.1.1 on 2022-10-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0014_alter_deal_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="deal", name="type",),
    ]
