# Generated by Django 4.1.1 on 2022-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0016_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminpanel",
            name="profit_risk",
            field=models.FloatField(default=0),
        ),
    ]
