# Generated by Django 4.1.1 on 2022-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0017_adminpanel_profit_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminpanel",
            name="profit_balance",
            field=models.FloatField(default=0),
        ),
    ]
